[project]
name = "concise-reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.4.0",
    "datasets>=3.3.2",
    "llmlingua>=0.2.2",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
